scrape_configs:
  - job_name: Confluent Cloud
    scrape_interval: 1m
    scrape_timeout: 1m
    honor_timestamps: true
    static_configs:
      - targets:
        - api.telemetry.confluent.cloud
    scheme: https
    basic_auth:
      username: CCLOUD_API_KEY
      password: CCLOUD_SECRET
    metrics_path: /v2/metrics/cloud/export
    params:
      resource.kafka.id: [lkc-xxx]      
  - job_name: "quarkus_kafka_streams"
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: /q/metrics/prometheus
    scheme: http
    static_configs:
      - targets: 
        - host.docker.internal:8080
